### ISSUE TITLE
Failed to activate the welcome package

### ISSUE THREAD

**Issue by t1bor** [atom/welcome#35]
[Enter steps to reproduce below:]

1. Disable package.
2. Re-enable package.

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.2
**Thrown From**: [welcome](https://github.com/atom/welcome) package, v0.27.0

### Stack Trace

Failed to activate the welcome package

```
At Cannot read property 'length' of null

TypeError: Cannot read property 'length' of null
  at Object.module.exports.setReporter (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/welcome/lib/reporter.js:9:32)
  at Object.module.exports.consumeReporter (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/welcome/lib/welcome.js:93:23)
  at Provider.module.exports.Provider.provide (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:34)
  at ServiceHub.module.exports.ServiceHub.consume (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:48:18)
  at Package.module.exports.Package.activateServices (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:380:69)
  at Package.module.exports.Package.activateNow (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:241:16)
  at /Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
  at Package.module.exports.Package.measure (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.activate (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
  at /Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:303:19
  at /Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:148:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:132:14)
  at HTMLButtonElement.<anonymous> (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:252:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Users/tkecskemeti/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -3:38.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:38.5.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -3:38.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:36.6.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -3:36.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:34.5.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -3:34.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:32.6.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -3:32.6.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -3:31.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -3:31.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:31.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -3:31.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -3:31.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:31.8.0 editor:indent (atom-text-editor.editor.is-focused)
 11x -3:31.5.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "w3c-validation",
      "linter"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "welcome": {
    "showOnStartup": false
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @t1bor -- I was able to reproduce this with your instructions. /cc @benogle @kevinsawicki for :eyes:
